### ISSUE TITLE
Warning about the .exe

### ISSUE THREAD

**Issue by saroqe** [saroqe/PyCMD#4]
**Describe the bug**
Converting the .py to .exe strangely exits the program on input

**To Reproduce (how did this issue happen?)**
Giving input the the .exe

**Screenshots**

If you are building an OS:
What was the error message?

did it run?

How did you install the Terminal.

**Additional context**
The terminal basically is useless when used on an OS.

**Comment by Vepsiee** [comment]
Resolved, it just seemed to fix itself.
